// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Child from "./Child.bs.js";

function createScript($$document) {
  return $$document.createElement("script");
}

function listener(iframe, param) {
  if (param.origin === location.origin) {
    iframe.height = param.data.height.toString() + "px";
    return ;
  }
  
}

function start(iframe) {
  window.addEventListener("message", (function (param) {
          return listener(iframe, param);
        }));
}

function stop(iframe) {
  window.removeEventListener("message", (function (param) {
          return listener(iframe, param);
        }));
}

function make(iframe) {
  var contentWindow = iframe.contentWindow;
  start(iframe);
  var $$document = contentWindow.document;
  var script = $$document.createElement("script");
  script.textContent = ";(" + Child.toString(Child.make) + ")();";
  $$document.body.appendChild(script);
  return iframe;
}

export {
  createScript ,
  listener ,
  start ,
  stop ,
  make ,
}
/* No side effect */
